version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/astro"
    schedule:
      interval: "monthly"
    groups:
      astro-deps:
        patterns:
        - "*"
  - package-ecosystem: "npm"
    directory: "/payload"
    schedule:
      interval: "monthly"
    groups:
      payload-deps:
        patterns:
        - "*"
