services:
  astro:
    build:
      target: dev
    volumes:
      - ./astro:/base
      - /base/node_modules/
    ports:
      - 3000:3000

  payload:
    build:
      target: dev
    volumes:
      - ./payload/src:/base/src
      - ./astro/src/types.ts:/types.ts
    ports:
      - 3001:3001

  mongo:
    ports:
      - 27017:27017
