services:
  astro:
    build:
      context: astro
      target: prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}-astro.rule=Host(`${ASTRO_HOST}`)"
      - "traefik.http.routers.${NAME}-astro.entrypoints=https"
      - "traefik.http.routers.${NAME}-astro.tls.certresolver=httpresolver"
      - traefik.docker.network=traefik_network
    networks:
      - traefik_network

  payload:
    build:
      context: payload
      target: prod
    volumes:
      - ./data/media:/prod/dist/media
    environment:
      - REPOSITORY=${REPOSITORY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}-payload.rule=Host(`${PAYLOAD_HOST}`)
      - traefik.http.routers.${NAME}-payload.entrypoints=https
      - traefik.http.routers.${NAME}-payload.tls.certresolver=httpresolver
      - traefik.docker.network=traefik_network
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
